### ISSUE TITLE
[Market] Overdue storage order dealing 

### ISSUE THREAD

**Issue by zikunfan** [crustio/crust#155]
Including:
1. Cut `overdue sorder` occupied pledge;
2. Remove `overdue sorder` detail info (`StorageOrders`);

**Comment by zikunfan** [comment]
Add cut pledge for the overdue storage order for provider. @BOBOKaa

**Comment by MyronFanQiu** [comment]
@zikunfan Is this issue same with #138?

**Comment by MyronFanQiu** [comment]
### Draft Design
- Market
Entry Point. Will call Tee and Payment's interface. Will expose Market Interface for Tee and expose extrinse for providers and clients to cancel their own storage. Slash would also call `close_sorder` to close sorder.
- Payment
Will provide interface to remove related information for closed sorder.
- Tee
Will provide interface to remove related information for closed sorder.
Will call Market's interface to set sorder to closed in passive check.(Or we can also do it in market. `on_initialized`)
