### ISSUE TITLE
[GPoS] Align ErasValidatorPref with Polkadot

### ISSUE THREAD

**Issue by MyronFanQiu** [crustio/crust#306]
Now pref is used to calculate the total value of guarantors, which is not align with polkdot.

**Comment by MyronFanQiu** [comment]
If we do this, subscan won't change anymore.

**Comment by zikunfan** [comment]
Remove from M2

**Comment by MyronFanQiu** [comment]
Don't do it in chain. Need to change subscan and app.

**Comment by zikunfan** [comment]
> Don't do it in chain. Need to change subscan and app.

So we close it.
