### ISSUE TITLE
ERROR 10003

### ISSUE THREAD

**Issue by VadimkKorolev** [crustio/crust#337]
[Dec  2 2020 09:55:14.535] [ERROR] Send work report to crust chain failed!
[Dec  2 2020 09:55:14.535] [ERROR] Get signed validation report failed! Error code: 10003.Help me please to fix this Error!
My telegram @Dobroxob

**Comment by LowEntropyBody** [comment]
Check the synchronization status of your chain and ensure that the control account has enough CRU money
