### ISSUE TITLE
[Investigation] Block time is not stable in cc2 (around 7s)

### ISSUE THREAD

**Issue by MyronFanQiu** [crustio/crust#351]

**Comment by MyronFanQiu** [comment]
[telemetry.polkadot.io-1608263862604.log](https://github.com/crustio/crust/files/5713573/telemetry.polkadot.io-1608263862604.log)
After analyze the log, it looks like that work report would affect block number. The operational dispatch class might be the reason.

**Comment by MyronFanQiu** [comment]
`--execution wasm` turns out that report_works and register in swork need 200x weight than `--execution native`

**Comment by MyronFanQiu** [comment]
we should run with `--execution wasm --wasm-execution compiled` witch just 10x times than native! I dodo the test and it work. https://github.com/paritytech/substrate/issues/7779

**Comment by zikunfan** [comment]
> we should run with `--execution wasm --wasm-execution compiled` witch just 10x times than native! I dodo the test and it work. [paritytech/substrate#7779](https://github.com/paritytech/substrate/issues/7779)

Resolved by this method
