### ISSUE TITLE
Hard disk error

### ISSUE THREAD

**Issue by steenboy** [crustio/crust#353]
After a hard disk error occurs, if you crust stop, you can no longer crust start, even if the path is removed from the configuration file, how should this be handled? (If you don’t stop, work will continue)。

**Comment by zikunfan** [comment]
> After a hard disk error occurs, if you crust stop, you can no longer crust start, even if the path is removed from the configuration file, how should this be handled? (If you don’t stop, work will continue)。

AFAIK, there is no `stop` command in [crust-node](https://github.com/crustio/crust-node), what do you mean **no longer do the crust start**?

**Comment by MyronFanQiu** [comment]
close this issue since no response. Feel free to raise new issue if you still encounter any problem.
