### ISSUE TITLE
安装 ipfs desktop 之时出现了一个不支持32位系统进行安装的BUG

### ISSUE THREAD

**Issue by qilin6835** [crustio/crust#483]
我的电脑是32位系统却弹出了一个  ipfs desktop 安装窗口的提示，
内容问题 ：需要 64位  windows 系统，
也就是说：安装 ipfs desktop这个时  出现了一个**不兼容32位系统的BUG** ; 
![image](https://user-images.githubusercontent.com/39442588/107870397-0a022680-6ed3-11eb-8226-7a56dc1932b6.png)

**Comment by zikunfan** [comment]
尝试打包32位安装包中 @gavfu

**Comment by zikunfan** [comment]
解决了，下个版本即将上线

**Comment by zikunfan** [comment]
5000 Candies
