### ISSUE TITLE
提交了很久一直没有反应

### ISSUE THREAD

**Issue by xedl123** [crustio/crust#489]
![image](https://user-images.githubusercontent.com/79250418/108371333-9fd1e480-7238-11eb-9466-41f5d5ae7e84.png)
CID ：QmZjU7Mqxa8KBy9Hejp9qtfcERVd8nGq3AQnP4hSwEhF7x

账号：5Ca8t6fMP6kLZo3cB4PHFNYDsML5R3w1F9Kis9CTNaFpqYZT

**Comment by MyronFanQiu** [comment]
可以查看一下你ipfs的防火墙关了没有，现阶段的指南里面少了一个步骤，后续会更新文档以及修复

**Comment by xedl123** [comment]
> 可以查看一下你ipfs的防火墙关了没有，现阶段的指南里面少了一个步骤，后续会更新文档以及修复

不知道在哪里看，等你们的更新吧
