### ISSUE TITLE
Website redirection can be optimized

### ISSUE THREAD

**Issue by 15226342722** [crustio/crust#490]
Website redirection can be optimized, not a network node problem, See below [http://42.192.188.70/a33.png](http://42.192.188.70/a33.png)

**Comment by MyronFanQiu** [comment]
@15226342722 It's not a problem of our project. Something can be optimized in our dependency. We can try to fix it but it may take some time. @yuhui1208 Please take a look when you have time.

**Comment by zikunfan** [comment]
Basically we port https://github.com/polkadot-js/apps, redirection and loading issue can be submit [here](https://github.com/polkadot-js/apps/issues)
Close it first.
