### ISSUE TITLE
上传文件后，分享链接打不开

### ISSUE THREAD

**Issue by xianxianzhou** [crustio/crust#493]
https://ipfs.io/ipfs/QmUFRQ129QXub6LRo8w8VusCGzcDa8yPY5qnYdzpBa4Pzr?filename=logocoffee.png

上传文件后，本地可查看，但是分享链接是打不开的

**Comment by zikunfan** [comment]
有人帮你接单吗？看看存储市场，你的文件是否处于pending状态，并且请保证关闭防火墙，否则别的节点拉不到你的文件，关闭防火墙后，请重启ipfs客户端

**Comment by MyronFanQiu** [comment]
close it due to no response. If you have any more question, please feel free to raise a new issue
