### ISSUE TITLE
Find unfriendly

### ISSUE THREAD

**Issue by sky654** [crustio/crust#494]
1. After uploading the picture, the window will display friendly links.
![1613803259(1)](https://user-images.githubusercontent.com/79191806/108586468-ba67a300-7389-11eb-9b4e-9c368552470c.png)

2. Store. Doc file to IPFs, and display garbled code after downloading through CID.

3. After storing the photo file to IPFs for 24 hours, the number of crust copies will not be displayed.
![1613803634(1)](https://user-images.githubusercontent.com/79191806/108586630-bc7e3180-738a-11eb-8793-95d6e1fe1fff.png)

**Comment by sky654** [comment]
5FmyHgFhmnZWttkvwFj5Bo7oakoNgP4HXVZLn1tCyt3eCcwX

**Comment by sky654** [comment]
5FmyHgFhmnZWttkvwFj5Bo7oakoNgP4HXVZLn1tCyt3eCcwX

**Comment by zikunfan** [comment]
1000 Candies
