### ISSUE TITLE
cannot receive file storage order

### ISSUE THREAD

**Issue by halcyon-zihao** [crustio/crust#508]
We found an issue that if we do not turn off the firewall on macOS 11.3, we cannot see the order of files we uploaded to be received on Crust network, say, no update in Crust Replicas.

**Comment by MyronFanQiu** [comment]
Thanks for the suggestion. We have already discovered this issue. We have added some instruction on our crust-apps and will update it later.

**Comment by halcyon-zihao** [comment]
address: 5Di1PvD5T8FoB1s3N6ywHKvWvPEpfXRKKKK8RpwVEdckWjat

**Comment by halcyon-zihao** [comment]
> Thanks for the suggestion. We have already discovered this issue. We have added some instruction on our crust-apps and will update it later.

5Di1PvD5T8FoB1s3N6ywHKvWvPEpfXRKKKK8RpwVEdckWjat

**Comment by MyronFanQiu** [comment]
close it due to outdated. If you have any more question, please feel free to raise a new issue
