### ISSUE TITLE
error from daemon in stream: Error grabbing logs: unexpected EOF

### ISSUE THREAD

**Issue by liang7173** [crustio/crust#543]
[Mar 23 2021 05:49:29.611] [INFO] [Enclave] Seal random data -> a24846d988da85ce266f9bc62d4db20a526971f1f660234b18feff0b2e6f2a01, 6593G success
[Mar 23 2021 05:49:29.825] [INFO] [Enclave] Seal random data -> 5df98237193845ffc051426fc7b1c8bad165b9a6a0d1337c3e888a09b3d05cf5, 6594G success
[Mar 23 2021 05:49:29.876] [INFO] [Enclave] Seal random data -> e35934cf1f94919e85ae851bfe8692057e6e6ac3565d63b89af5a174ce7adc9f, 6595G success
[Mar 23 2021 05:49:30.816] [INFO] [Enclave] Seal random data -> 1537a029d07d7bc53261f4305227b28f18edff06e4231fb4ed29a24f5977e6f3, 6596G success
[Mar 23 2021 05:49:30.889] [INFO] [Enclave] Seal random data -> 74bbd54c06855313dff97a909c7defaa808fcac5e297e55b7304a0974dc13045, 6597G success
[Mar 23 2021 05:49:31.164] [INFO] [Enclave] Seal random data -> 64ca703d7397d5162bbff8656303b503cad6ea1db73abf6067fe68b2f160770d, 6598G success
[Mar 23 2021 05:49:35.039] [INFO] [Enclave] Seal random data -> 5c3a60898bf62792d6b6bda5d76a3e2c4aa0a45ec784a043ee8ee62cd62c69f2, 6599G success
[Mar 23 2021 05:49:43.478] [INFO] [Enclave] Seal random data -> e3fbb8a153f054d4094882886580d79fce3cc884a898b01351bbdcc7db9ae147, 6600G success
[Mar 23 2021 05:51:20.223] [ERROR] Chain result: {"status":"error","message":"Response timeout"}, wait 10s and try again
[Mar 23 2021 05:51:32.428] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385063937871): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:51:43.335] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385061208291): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:52:29.050] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385058478711): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:52:51.775] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385057113501): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:53:03.183] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385054383501): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:53:23.010] [INFO] [Enclave] Seal random data -> 8a7fc8eab103592be3d28db57ddfb2dd7d82e0eccad9fa99067c7ccf40ed29a4, 6601G success
[Mar 23 2021 05:53:23.247] [INFO] [Enclave] Seal random data -> da181835ce583e42f70ece64d7f3c1fa2846647423e4f884cab95b30587582c0, 6602G success
[Mar 23 2021 05:53:24.218] [INFO] [Enclave] Seal random data -> 97130db4380f157f04456b83ee1213c7fdcb1f49f26aefafa73905fd1d38ca7b, 6603G success
[Mar 23 2021 05:53:27.365] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385053017871): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:53:29.134] [INFO] [Enclave] Seal random data -> 413f5a6e245ebf57ea2f3bdb0139bc97fbf93eff668606ca2f8f9f1e18a4a47b, 6604G success
[Mar 23 2021 05:53:32.346] [INFO] [Enclave] Seal random data -> da83ba891f421b86485a63245718dc5953a23e3c469a8396512d6b8b0a115266, 6605G success
[Mar 23 2021 05:53:33.174] [INFO] [Enclave] Seal random data -> c06579abac9793870e9e46fbb700d4a7c316db215be476163e2aae98888b129a, 6606G success
[Mar 23 2021 05:53:33.850] [INFO] [Enclave] Seal random data -> a9bcb4217da401fae243323fcb87d35924de59027da1e9f732405e6ad4b603a8, 6607G success
[Mar 23 2021 05:53:36.314] [INFO] [Enclave] Seal random data -> b059bf3ad14c5cdcad9fb6a3e6e726915584c4552b63c38a2a068e2ae1487742, 6608G success
[Mar 23 2021 05:53:58.688] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385051652241): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:54:14.847] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385050969531): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:54:26.620] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385047555561): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:55:11.624] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385046189931): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:55:23.768] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385044141591): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:56:03.263] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385042775961): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:56:15.461] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385039362201): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:56:45.175] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385038679491): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:57:08.444] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385036631151): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:57:19.173] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385033900101): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:57:22.338] [INFO] [Enclave] Seal random data -> 024c849182ae52b0277c2f21a711aea6620d9c4d562200d75b2bc35042f5fee3, 6609G success
[Mar 23 2021 05:57:29.669] [INFO] [Enclave] Seal random data -> 0fc65750d546444a0fd06cf16a44dcc8cdf6a56eaf1b5a55c3deca794205f5e3, 6610G success
[Mar 23 2021 05:57:30.342] [INFO] [Enclave] Seal random data -> 6d9089077c1eaccc8d37adb28399ac78398f8f3744a3a9bcf61ce364ec1700c9, 6611G success
[Mar 23 2021 05:57:30.348] [INFO] [Enclave] Seal random data -> 0fa05c428994bcd89cc34a650e20302aa0ec2c183dd5cfd186b3d7e83a7dc12e, 6612G success
[Mar 23 2021 05:57:30.385] [INFO] [Enclave] Seal random data -> 4252015914dbf498117a63e1f6d78c9a5971413016d5a4e54c556c45418e4dcb, 6613G success
[Mar 23 2021 05:57:34.953] [INFO] [Enclave] Seal random data -> e0941e5c15fd18b5b01d654d1d494cc3d9ea8842a2e0f0489b116d0f10749bf8, 6614G success
[Mar 23 2021 05:57:35.403] [INFO] [Enclave] Seal random data -> f11161ca1c7cda563cdc8b576b958a3c8305385b77b793ed29ad31c044a6fe8e, 6615G success
[Mar 23 2021 05:57:36.005] [DEBUG] Http request:/api/v0/storage/seal
[Mar 23 2021 05:57:36.005] [INFO] Dealing with seal request(file cid:'QmRJWH5xjDTSfw6fx1REhZxGaL6vvNdZhcHC8xh7y7Y3rz')...
[Mar 23 2021 05:57:36.698] [INFO] [Enclave] Seal random data -> a2d45a6b0ae9fdc61a4ee4ff32c7b5b7e5763571214e2943ec17b0a2315bdfdc, 6616G success
[Mar 23 2021 05:58:02.821] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385031851761): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:58:29.291] [INFO] [Enclave] Seal complete, file info; cid: QmRJWH5xjDTSfw6fx1REhZxGaL6vvNdZhcHC8xh7y7Y3rz -> size: 209765109, status: valid
[Mar 23 2021 05:58:29.291] [INFO] Seal file 'QmRJWH5xjDTSfw6fx1REhZxGaL6vvNdZhcHC8xh7y7Y3rz' successfully
[Mar 23 2021 05:58:29.329] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385029803631): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:58:44.135] [ERROR] Chain result: {"status":"error","message":"1014: Priority is too low: (13835058385064620161 vs 13835058385027756131): The transaction has too low priority to replace another transaction already in the pool."}, wait 10s and try again
[Mar 23 2021 05:58:54.135] [ERROR] Send work report to crust chain failed!
error from daemon in stream: Error grabbing logs: unexpected EOF

Usage: crust logs [OPTIONS] {chain|api|sworker|sworker-a|sworker-b|smanager|ipfs}

Fetch the logs of a service

Options:
      --details        Show extra details provided to logs
  -f, --follow         Follow log output
      --since string   Show logs since timestamp (e.g. 2013-01-02T13:23:37) or relative (e.g. 42m for 42 minutes)
      --tail string    Number of lines to show from the end of the logs (default "all")
  -t, --timestamps     Show timestamps
      --until string   Show logs before a timestamp (e.g. 2013-01-02T13:23:37) or relative (e.g. 42m for 42 minutes)

**Comment by LowEntropyBody** [comment]
There are two reasons for the error. First, your chain synchronization is unstable. Please change to a better network. The second is docker's error. For details, please refer to https://github.com/docker/for-mac/issues/1984

**Comment by MyronFanQiu** [comment]
close this issue since it should be already resolved. Feel free to open a new issue if you encounter any more problem.
