### ISSUE TITLE
[GPoS] Stage 2 Stake Limit Calculation

### ISSUE THREAD

**Issue by MyronFanQiu** [crustio/crust#551]

**Comment by zikunfan** [comment]
# Stake Limit Calculation Mechanism Brief Introduction

Stake Limit Calculation combine with 2 parts: a `curve set` and a `2 stages-curve`, curve-set decides a key param of the `2 stages-curve`, and the `2 stages-curve` decides node's stake limit.

## 1. Curve Set

Curve set decides a param named `Stake Limit cut-off point`(SL Cut-Off Point), which decides the total stake limit the nodes can stake, initial with `60%`, and this SL Cut-Off Point decided by the total effective stakes rate, which `= total_effective_stakes / total_issued`.
![3981619001312_ pic_hd](https://user-images.githubusercontent.com/10335300/115540149-5fdabc80-a2d0-11eb-9489-588b9216b9b7.jpg)

## 2. 2 Stages-curve

2 stages-curve truly decided the Stake Limit, which divided into 2 stages, 1st stage is static ratio with storage power(initial with 1:5), and the 2nd stage will comparing with total storages, and the transforming condition is decided by the `SL Cut-Off Point` from `Curve Set` shows below.

![3991619001313_ pic_hd](https://user-images.githubusercontent.com/10335300/115541242-7af9fc00-a2d1-11eb-8eaa-9d9a90cec0a1.jpg)
