### ISSUE TITLE
Crash when start owner on Cloud host.

### ISSUE THREAD

**Issue by jerry-sl** [crustio/crust#557]
ENV:  Alibaba ECS cloud   ubuntu 18.04
Command:   sudo crust logs chain 

logs:

sudo crust logs chain
2021-04-04 02:32:53  Crust
2021-04-04 02:32:53  ✌️  version 0.11.1-4c3dc21-x86_64-linux-gnu
2021-04-04 02:32:53  ❤️  by crustio, 2019-2021
2021-04-04 02:32:53  📋 Chain specification: Crust Maxwell
2021-04-04 02:32:53  🏷 Node name: jxowner
2021-04-04 02:32:53  👤 Role: AUTHORITY
2021-04-04 02:32:53  💾 Database: RocksDb at /opt/crust/data/chain/chains/crumwl/db
2021-04-04 02:32:53  ⛓  Native runtime: crust-1 (crustio-crust-1.tx1.au1)
2021-04-04 02:32:53  🔨 Initializing Genesis block/state (state: 0xd605…389e, header-hash: 0xb19e…d41f)
2021-04-04 02:32:53  👴 Loading GRANDPA authority set from genesis on what appears to be first startup.

====================

Version: 0.11.1-4c3dc21-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:495:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:50:5
   7: raw_cpuid::CpuId::get_extended_feature_info
   8: cranelift_native::builder
   9: wasmtime_jit::native::builder
  10: wasmtime::runtime::Config::new
  11: sc_executor_wasmtime::runtime::create_runtime
  12: sc_executor::wasm_runtime::create_wasm_runtime_with_code
  13: sc_executor::wasm_runtime::create_versioned_wasm_runtime
  14: sc_executor::wasm_runtime::RuntimeCache::with_instance
  15: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  16: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  17: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  18: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::call
  19: <alloc::sync::Arc<dyn sc_client_api::call_executor::ExecutorProvider<Block>+Executor = E> as sc_finality_grandpa::GenesisAuthoritySetProvider<Block>>::get
  20: sc_finality_grandpa::aux_schema::load_persistent
  21: crust::service::new_partial
  22: crust::service::new_full
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: std::thread::local::LocalKey<T>::with
  25: tokio::runtime::thread_pool::ThreadPool::block_on
  26: tokio::runtime::context::enter
  27: sc_cli::runner::Runner<C>::run_node_until_exit
  28: crust::command::run
  29: crust::main
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: std::rt::lang_start::{{closure}}
  32: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panic.rs:396:14
      std::rt::lang_start_internal
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/rt.rs:51:25
  33: main
  34: __libc_start_main
  35: _start

Thread 'main' panicked at 'assertion failed: res.eax == 0', /opt/cache/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-7.0.3/src/lib.rs:295

This is a bug. Please report it at:

	https://github.com/crustio/crust/issues/new

**Comment by MyronFanQiu** [comment]
Which cloud are you using? Could you provide some information? As a workaround to solve this issue, you can go to modify the docker-compose.yml in /opt/crust/crust-data/build/ path and remove the `--wasm-execution` and `compiled` from the args of chain and use `sudo docker-compose up -d crust` to try again.

**Comment by MyronFanQiu** [comment]
close this issue since we cannot do too much for this.
