### ISSUE TITLE
Plan to extend SGX remote attestation to DCAP/ECDSA attestation?

### ISSUE THREAD

**Issue by ligangwangx** [crustio/crust#592]
According to [Intel SGX Remote Attestation Portal](https://software.intel.com/content/www/us/en/develop/topics/software-guard-extensions/attestation-services.html), SGX EPID-based remote attestation is not available on 3rd Gen Xeon-SP (codenamed Ice Lake). 3rd Gen Xeon-SP only supports ECDSA-based attestation. Does the Crust community have a plan to support ECDSA-based attestation, so that Crust can run on 3rd Gen Xeon-SP to leverage its more powerful performance and much larger EPC size?

**Comment by MyronFanQiu** [comment]
@LowEntropyBody @TonyCode2012 Could you please share some ideas here?

**Comment by MyronFanQiu** [comment]
@ligangwangx I saw you already open a new issue https://github.com/crustio/crust-sworker/issues/364 in sworker repo. Let's close this issue so that we can focus on the only one issue.
