### ISSUE TITLE
[Market] File double order should cancel the expiring extension

### ISSUE THREAD

**Issue by zikunfan** [crustio/crust#627]
## Elder way
Like File A's `expired_bn = 100`, now is `bn = 120`. When I re-order File A, I should pay the expired 20 blocks money

## Proposal
Case shows above, when I re-order File A, I do not need pay anything cause File A may not placed by me before.

**Comment by zikunfan** [comment]
@ysh0566

**Comment by mmyyrroonn** [comment]
#670
