### ISSUE TITLE
根据github网址无法成功部署节点

### ISSUE THREAD

**Issue by jsonMark** [crustio/crust#671]
参考手册网址:
Crust 激励测试网单节点手册
https://github.com/crustio/crust/wiki/Crust-激励测试网单节点手册
问题:
![image](https://user-images.githubusercontent.com/27055049/125431724-4bd832e7-82b5-42f4-af0b-7cf0d07f32f6.png)
![image](https://user-images.githubusercontent.com/27055049/125431831-f1f3bba5-3f6d-4204-bb77-f4b094520abf.png)

**Comment by jsonMark** [comment]
![image](https://user-images.githubusercontent.com/27055049/125431981-a0061a27-86d3-4586-9679-4ee4c62c96b5.png)
![image](https://user-images.githubusercontent.com/27055049/125432009-e9f7639f-3e97-4825-9837-2866fdfba752.png)
环境:Ubuntu18，服务器阿里云

**Comment by MyronFanQiu** [comment]
@jsonMark Github的wiki已经过时了，请参照 https://wiki.crust.network/docs/zh-CN/ownerNode 进行部署
