### ISSUE TITLE
how to get all accounts

### ISSUE THREAD

**Issue by vanxizzz** [crustio/crust#672]
How to get **all accounts,** including verifier, nominator, candidate verifier, Council, technical committee and so on... I found https://crust.subscan.io/account?role=all Yes, but I can't find the corresponding API in the crust document

**Comment by MyronFanQiu** [comment]
api.query.system.accounts.entries()

**Comment by vanxizzz** [comment]
> api.query.system.accounts.entries()

i call this api , but api.query.system.accounts return undefined
