### ISSUE TITLE
How to query unfrozen lock

### ISSUE THREAD

**Issue by vanxizzz** [crustio/crust#685]
I found that in the data returned by **api.query.balances.locks**, the ID of 0x7374616b696e6720 is pledge, the ID of 0x706872656c656374 is election lock, and the ID of 0x64656d6f6372763 is democratic lock. **What's the unfrozen ID?** I'll refer to it **https://crust.subscan.io/account/5G4ch9r3xoxUUGoWLbTGJzke419FbkhoNCVTxotCQQALp8tw**

**Comment by vanxizzz** [comment]
help me , please!!!

**Comment by mmyyrroonn** [comment]
api.query.balances.locks

**Comment by mmyyrroonn** [comment]
ID is just a string

**Comment by mmyyrroonn** [comment]
https://apps.crust.network/docs/

**Comment by vanxizzz** [comment]
我找不到一个含有解冻中的账户，所以我通过api.query.balances.locks也不知道解冻中的ID是什么，可以告诉我吗！

**Comment by mmyyrroonn** [comment]
@vanxizzz 你可以去rocky上直接把你自己的账户锁一点 比如民主模块或者小费啥的
