### ISSUE TITLE
how to query extrinsic service fee

### ISSUE THREAD

**Issue by vanxizzz** [crustio/crust#686]
i refer the subscan. example: https://crust.subscan.io/extrinsic/2458889-1

**Comment by vanxizzz** [comment]
help me , please !!

**Comment by mmyyrroonn** [comment]
I don't know the answer either. According to subscan, there must be a way to do it. Maybe you can go to subscan's repo for help

**Comment by vanxizzz** [comment]
I see the transaction fee for using the network in the technical document. How can I get this fee through the interface? The original text is like this: **as a transaction fee for using net**
