### ISSUE TITLE
help me , please!!!!!

### ISSUE THREAD

**Issue by vanxizzz** [crustio/crust#689]
可以告诉我，总存储量，最低质押量，每T质押量，平均质押量，可质押总量怎么计算吗
以下所说的验证人包括候选验证人
1.总存储量是所有验证人的质押上限相加吗
2.最低质押量是所有有效质押最低的验证人吗
3.每T质押量是api.consts.staking.sPowerRatio返回值吗
4.平均质押量是可质押总量除以验证人个数吗
5.可质押总量是所有验证人的质押总量相加吗

Can you tell me how to calculate the total reserves, the minimum amount of pledge, the amount of pledge per T, the average amount of pledge and the total amount of pledge

The verifiers mentioned below include candidate verifiers

1.Is the total reserve the sum of the pledge limits of all verifiers

2.Is the minimum pledge the lowest verifier of all valid pledges

3.Is the pledge amount per t the return value of api.consts.stacking.spowerratio

4.Is the average amount of pledge the total amount of pledge divided by the number of verifiers

5.Can the total amount of pledge be the sum of the total amount of pledge of all verifiers

**Comment by mmyyrroonn** [comment]
总存储量是指Crust网络的文件存储量还是指可用的总存储量？文件存储量可以在swork.reported_files_size里面，已保留未用的总量是swork.free，两者相加就是总存储量。不是很理解最低质押量是什么，并没有这个东西。每T质押量是api.consts.staking.sPowerRatio。平均质押量的是质押总量除以所有validators的数目。可质押量不是很理解，Crust网络里面没有这个定义，如果是二层业务需求取决于定义。我能联想到的是关于质押上限减去已质押的剩余量的总和。
