### ISSUE TITLE
怎么获取验证人的得分

### ISSUE THREAD

**Issue by vanxizzz** [crustio/crust#707]
https://apps.crust.network/#/staking这里面的验证人得分，是通过调用哪个接口获取的呀

**Comment by vanxizzz** [comment]
help me !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by vanxizzz** [comment]
@MyronFanQiu

**Comment by vanxizzz** [comment]
@MyronFanQiu   对了，我想获取详细的交易费用，但是api.rpc.payment.queryFeeDetails提示queryFeeDetails不是函数，然后api.rpc.payment.queryInfo的话我是传了交易的哈希地址和区块哈希地址，但是也一直报错
api.rpc.payment.queryInfo('0x2c3d43f05ce572513d52e1ed243aa09bfa98d26e1c9dd99d1318bfc915be8bb1' , '0xd12aa8d1cf1a963e04d89f18e347d3c119c04d39acb5655901c2e34071c83c85')

**Comment by vanxizzz** [comment]
救命！！ save me！！@MyronFanQiu

**Comment by vanxizzz** [comment]
得分已经获取到了，帮我解答下这个，谢谢

> @MyronFanQiu 对了，我想获取详细的交易费用，但是api.rpc.payment.queryFeeDetails提示queryFeeDetails不是函数，然后api.rpc.payment.queryInfo的话我是传了交易的哈希地址和区块哈希地址，但是也一直报错
> api.rpc.payment.queryInfo('0x2c3d43f05ce572513d52e1ed243aa09bfa98d26e1c9dd99d1318bfc915be8bb1' , '0xd12aa8d1cf1a963e04d89f18e347d3c119c04d39acb5655901c2e34071c83c85')

**Comment by mmyyrroonn** [comment]
> 得分已经获取到了，帮我解答下这个，谢谢
> 
> > @MyronFanQiu 对了，我想获取详细的交易费用，但是api.rpc.payment.queryFeeDetails提示queryFeeDetails不是函数，然后api.rpc.payment.queryInfo的话我是传了交易的哈希地址和区块哈希地址，但是也一直报错
> > api.rpc.payment.queryInfo('0x2c3d43f05ce572513d52e1ed243aa09bfa98d26e1c9dd99d1318bfc915be8bb1' , '0xd12aa8d1cf1a963e04d89f18e347d3c119c04d39acb5655901c2e34071c83c85')

这个确实接口是一个预测下一个交易手续费的价格，并不是获取历史交易手续费的价格。我所了解的区块里面会有两笔转账可以获得手续费，分别是是treasury.deposit和balance.deposit
