### ISSUE TITLE
建立watch的时候报错bug

### ISSUE THREAD

**Issue by laozhang713** [crustio/crust#749]
2021-09-13 10:45:13  👤 Role: FULL    
2021-09-13 10:45:13  💾 Database: RocksDb at /opt/crust/data/watchchain/chains/crust/db    
2021-09-13 10:45:13  ⛓  Native runtime: crust-4 (crustio-crust-1.tx1.au1)    
2021-09-13 10:45:13  👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    

====================

Version: 1.0.0-9a797de-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:495:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:50:5
   7: raw_cpuid::CpuId::get_extended_feature_info
   8: cranelift_native::builder_with_backend_variant
   9: cranelift_native::builder
  10: wasmtime_jit::native::builder
  11: wasmtime::config::Config::new
  12: sc_executor_wasmtime::runtime::create_runtime
  13: sc_executor::wasm_runtime::create_wasm_runtime_with_code
  14: sc_executor::wasm_runtime::create_versioned_wasm_runtime
  15: sc_executor::wasm_runtime::RuntimeCache::with_instance
  16: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
  17: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
  18: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
  19: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::call
  20: <alloc::sync::Arc<dyn sc_client_api::call_executor::ExecutorProvider<Block>+Executor = E> as sc_finality_grandpa::GenesisAuthoritySetProvider<Block>>::get
  21: sc_finality_grandpa::aux_schema::load_persistent
  22: sc_finality_grandpa::block_import
  23: crust::service::new_partial
  24: crust::service::new_full
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  26: std::thread::local::LocalKey<T>::with
  27: tokio::runtime::thread_pool::ThreadPool::block_on
  28: tokio::runtime::context::enter
  29: tokio::runtime::Runtime::block_on
  30: sc_cli::runner::Runner<C>::run_node_until_exit
  31: crust::command::run
  32: crust::main
  33: std::sys_common::backtrace::__rust_begin_short_backtrace
  34: std::rt::lang_start::{{closure}}
  35: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panic.rs:396:14
      std::rt::lang_start_internal
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/rt.rs:51:25
  36: main
  37: __libc_start_main
  38: _start

Thread 'main' panicked at 'assertion failed: res.eax == 0', /opt/cache/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-8.1.2/src/lib.rs:295

This is a bug. Please report it at:

        https://github.com/crustio/crust/issues/new

root@VM-0-6-ubuntu:~/crust-node-1.0.0#

**Comment by mmyyrroonn** [comment]
@laozhang713 有些机器的CPU不支持一些wasm的feature 一般是云机器 阿里云或者腾讯云都有遇到 重新换一下实例
