### ISSUE TITLE
How to get current session-key?

### ISSUE THREAD

**Issue by 0xshawn** [crustio/crust#762]
Hi,

I'm an operator of the curst cluster and to enhanced and robust the OPS of owner nodes, I have to get the current session-keys of it.

Is there any way to get it instead of just remember the result of `rotate-keys` result?

Thanks!

**Comment by mmyyrroonn** [comment]
You can call rpc method author_hasSessionKeys to check whether you locally has this key or not

**Comment by 0xshawn** [comment]
Thanks @MyronFanQiu
