### ISSUE TITLE
place_storage_order

### ISSUE THREAD

**Issue by alanmoleapfive** [crustio/crust#765]
place_storage_order
Return result Transaction hash
How to check whether the transaction has been successful
How to check whether a file has been successfully stored, or how to check the number of copies of a file
How to query all stored files under the same account

Is the input parameter in state_getStorage Market Files the CID in place_storage_order or what value?
What type of result is returned? I see that the result of the query is only 4 bytes

Whether the returned result is of this type
   FileInfo: {
     file_size:'u64',
     expired_on:'BlockNumber',
     calculated_at:'BlockNumber',
     amount:'Balance',
     prepaid:'Balance',
     reported_replica_count:'u32',
     replicas:'Vec<Replica<AccountId>>'
   }

**Comment by mmyyrroonn** [comment]
1. How to check whether the transaction has been successful
When you send the transaction, the Polkadot api would return the transaction result. You can also query the storage.market.files by inputting the CID to check the status of the file.
2. How to check whether a file has been successfully stored, or how to check the number of copies of a file
Directly query the chain's storage status "query.market.files" by inputting the cid. The result contains the number of copies of a file. 
3. How to query all stored files under the same account
You have to store all blocks locally to achieve this. This information is only stored in the blocks' extrinsic.

All types used in crust/Polkadot api can be found in https://github.com/crustio/crust.js/tree/mainnet/packages/type-definitions
