### ISSUE TITLE
Crust Shadow RPC endpoint

### ISSUE THREAD

**Issue by isSerge** [crustio/crust#811]
Hi guys, I am having issues connecting to the Crust Shadow node using `wss://rpc-shadow.crust.network/`
What alternative endpoints are available? Thanks

**Comment by mmyyrroonn** [comment]
Please try again. Something wrong about Caddy service and we already fixed it.

**Comment by isSerge** [comment]
Nothing changed, I still have:
```
 API-WS: disconnected from wss://rpc-shadow.crust.network/: 1006:: connection failed
 ```

**Comment by isSerge** [comment]
It seems to be fine now, but what's the plan for alternative endpoints? A single endpoint can go wrong anytime

**Comment by isSerge** [comment]
it's down again, any update?

**Comment by mmyyrroonn** [comment]
Should be fine right now. Feel free to reopen it if you meet any problem
