### ISSUE TITLE
`type_registry` update

### ISSUE THREAD

**Issue by PaTara43** [crustio/crust#891]
Hi!

I tried to work with a Crust network with the help of [py-substrate-interface](https://github.com/polkascan/py-substrate-interface). They have a `type_registry` [template](https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/crust.json#L46) for Crust network.

When I use the template and try to fetch chain state `market->filesV2`, which should return a `FileInfoV2` object, I get a `NotImplementedError: Decoder class for "FileInfoV2<AccountId, BalanceOf>" not found` which seems logic since there is no `FileInfoV2` object in the template, just the `FileInfo` one.

Okay, there is a way to modify the template. I found [this](https://github.com/crustio/crust/blob/ebb0d99c2041670b3d8f0ee9b914c15985fc2761/cstrml/market/src/lib.rs#L69)  description and tried to recreate it in the JSON format:
```
CRUST_TYPE_REGISTRY = {
    "types": {
        "FileInfoV2": {
            "type": "struct",
            "type_mapping": [
                ["file_size", "u64"],
                ["spower", "u64"],
                ["expired_at", "BlockNumber"],
                ["calculated_at", "BlockNumber"],
                ["amount", "Balance"],
                ["prepaid", "Balance"],
                ["reported_replica_count", "u32"],
                ["remaining_paid_count", "u32"],
                ["replicas", "BTreeMap<AccountId, Replica<AccountId>>"]
            ]
        },
        "Replica": {
            "type": "struct",
            "type_mapping": [
                ["who", "AccountId"],
                ["valid_at", "BlockNumber"],
                ["anchor", "SworkerAnchor"],
                ["is_reported", "Bool"],
                ["created_at", "Option<BlockNumber>"]
            ]
        },
    }
}
```

This results in `scalecodec.exceptions.InvalidScaleTypeValueException: Invalid value for datatype "bool"` error for the same chain state query. Seems like `is_reported` returns something but `bool`.

How can I perform this call?

p.s. other functions work fine: I use `market->placeStorageOrder` extrinsic and `system->account` chain state query.

**Comment by badkk** [comment]
> Hi!
> 
> I tried to work with a Crust network with the help of [py-substrate-interface](https://github.com/polkascan/py-substrate-interface). They have a `type_registry` [template](https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/crust.json#L46) for Crust network.
> 
> When I use the template and try to fetch chain state `market->filesV2`, which should return a `FileInfoV2` object, I get a `NotImplementedError: Decoder class for "FileInfoV2<AccountId, BalanceOf>" not found` which seems logic since there is no `FileInfoV2` object in the template, just the `FileInfo` one.
> 
> Okay, there is a way to modify the template. I found [this](https://github.com/crustio/crust/blob/ebb0d99c2041670b3d8f0ee9b914c15985fc2761/cstrml/market/src/lib.rs#L69) description and tried to recreate it in the JSON format:
> 
> ```
> CRUST_TYPE_REGISTRY = {
>     "types": {
>         "FileInfoV2": {
>             "type": "struct",
>             "type_mapping": [
>                 ["file_size", "u64"],
>                 ["spower", "u64"],
>                 ["expired_at", "BlockNumber"],
>                 ["calculated_at", "BlockNumber"],
>                 ["amount", "Balance"],
>                 ["prepaid", "Balance"],
>                 ["reported_replica_count", "u32"],
>                 ["remaining_paid_count", "u32"],
>                 ["replicas", "BTreeMap<AccountId, Replica<AccountId>>"]
>             ]
>         },
>         "Replica": {
>             "type": "struct",
>             "type_mapping": [
>                 ["who", "AccountId"],
>                 ["valid_at", "BlockNumber"],
>                 ["anchor", "SworkerAnchor"],
>                 ["is_reported", "Bool"],
>                 ["created_at", "Option<BlockNumber>"]
>             ]
>         },
>     }
> }
> ```
> 
> This results in `scalecodec.exceptions.InvalidScaleTypeValueException: Invalid value for datatype "bool"` error for the same chain state query. Seems like `is_reported` returns something but `bool`.
> 
> How can I perform this call?
> 
> p.s. other functions work fine: I use `market->placeStorageOrder` extrinsic and `system->account` chain state query.

Thanks for your feedback @PaTara43 ! @mmyyrroonn Would you mind take a look at this

**Comment by PaTara43** [comment]
Sorry for not closing the issue, this was solved in Discord
Types also updated for the template, though not released yet
https://github.com/polkascan/py-scale-codec/commit/6c897a0f09d3fadcb84eae393d98a831cf403b50 1.0.39 here
https://github.com/polkascan/py-substrate-interface/commit/5b0a0027df6c8b9c6f37d5346d803846594f110b 1.0.37 here
