### ISSUE TITLE
wasm `unreachable` instruction executed while Xstorage call on shadow

### ISSUE THREAD

**Issue by PaTara43** [crustio/crust#894]
Wile trying to perform `Xstorage -> placeStorageOrder` using https://github.com/polkascan/py-substrate-interface with this code:
```
    interface: SubstrateInterface = SubstrateInterface(
        url="wss://rpc-shadow.crust.network/",
        ss58_format=66,
        type_registry_preset="crust"
    )

    

    call = interface.compose_call(call_module="Xstorage", 
                                                   call_function="place_storage_order", 
                                                   call_params=dict(cid=ipfs_cid, size=file_size, currency_id="SelfReserve")
                                                   )
    signed_extrinsic = interface.create_signed_extrinsic(call=call, keypair=keypair)
    receipt = interface.submit_extrinsic(signed_extrinsic, wait_for_finalization=True)
    block_num: int = interface.get_block_number(receipt.block_hash)

    return receipt.extrinsic_hash, f"{block_num}-{receipt.extrinsic_idx}"
```

I get this error https://gist.github.com/PaTara43/8c5ca6d4c39f157347b3465dc2736229#file-error-log

This seems to be some sort of node issue, but I'm not sure, I was able to store a file via web-interface.

**Comment by mmyyrroonn** [comment]
which wss endpoint did you use?

**Comment by PaTara43** [comment]
`wss://rpc-shadow.crust.network/`

**Comment by mmyyrroonn** [comment]
> `wss://rpc-shadow.crust.network/`

It's a little bit strange. Maybe the call_module should be `xstorage`?

**Comment by PaTara43** [comment]
> > `wss://rpc-shadow.crust.network/`
> 
> 
> 
> It's a little bit strange. Maybe the call_module should be `xstorage`?

You mean the small 'x'?

I'll try that

**Comment by PaTara43** [comment]
> > `wss://rpc-shadow.crust.network/`
> 
> It's a little bit strange. Maybe the call_module should be `xstorage`?

```ValueError: Pallet 'xstorage' not found```

**Comment by khssnv** [comment]
There is no `xstorage` in a type registry for Crust Network for this python module: https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/crust.json. Could you create an issue in https://github.com/polkascan/py-scale-codec to support Crust Shadow and Crust Maxwell please, @PaTara43?

**Comment by PaTara43** [comment]
Sounds like this is not a type registry issue but a pallet discoverability @khssnv

**Comment by PaTara43** [comment]
https://github.com/polkascan/py-substrate-interface/issues/251
