### ISSUE TITLE
Error generating chainspec and metadata QR code for ParitySigner (PolkadotVault)

### ISSUE THREAD

**Issue by pgolovkin** [crustio/crust#926]
I'm generating chainspec and metadata QR code for [Metadata portal](https://metadata.novasama.io/#/) and getting error for crust-parachain from url `wss://crust-parachain.crustapps.net`.

The error is `Specs(Base58PrefixMismatch { specs: 66, meta: 88 })`

Please fix difference in the Base 58 prefix in spec and metadata. After that I'll be able to add Crust parachain to the metadata portal and Parity Signer (Polkadot Vault) cold wallet users will be able to operate Crust parachain.

**Comment by mmyyrroonn** [comment]
Fixed it. Please try again

**Comment by pgolovkin** [comment]
It works! Thank you!
You can find Crust metadata here https://metadata.novasama.io/#/polkadot-crust-parachain
