### ISSUE TITLE
How to get Crust metrics: CPU, GPU and memory benchmarking data.

### ISSUE THREAD

**Issue by stayForward09** [crustio/crust#937]
Hi, @team.
How are you?
I'm Davee from ev3.xyz, and we are going to add Crust key metrics to our official site https://depin.ninja/
And I've already got Storage Data for Crust from https://crust.subscan.io/storage, and now we wanna add CPU, GPU and memory benchmarking data for Crust.
Would you please help me to get relevant api to extract these metrics?
Thanks.

**Comment by veermetri05** [comment]
Hi, @stayForward09 .

Crust is only decentralized market place for storage. Crust doesn't provide any services related to CPU, GPU or other computations. Only the storage part of Crust can be utilized. Even though it might be possible to gather those metrics, it is not inherent part of Crust Network.

**Comment by stayForward09** [comment]
Thanks for your kind reply.
